blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/jaytotheay/qrm3/discussions/new?category=ideas
    about: Suggest an idea for this project
  - name: Support
    url: https://github.com/jaytotheay/qrm3/discussions/new?category=q-a
    about: Get help with qrm in GitHub Discussions
